models:
  - name: "SDXL 3.5 Medium"
    path: "stabilityai/stable-diffusion-3.5-medium"
    description: "Stable Diffusion 3.5 Medium (by Stability AI)."

  - name: "SDXL Turbo"
    path: "stabilityai/sdxl-turbo"
    description: "SDXL Turbo, ultra-fast text-to-image."

  - name: "SDXL Base"
    path: "stabilityai/stable-diffusion-xl-base-1.0"
    description: "SDXL Base, High quality images."

  - name: "SDXL Lightning"
    path: "ByteDance/SDXL-Lightning"
    description: "SDXL Lightning, High quality images."

  - name: "FLUX.1 [dev]"
    path: "black-forest-labs/FLUX.1-dev"
    description: "FLUX.1 [dev], rectified flow transformer for text-to-image generation." 
    
  - name: "Flux Midjourney"
    path: "strangerzonehf/Flux-Midjourney-Mix2-LoRA"
    description: "Flux Midjourney, rectified flow transformer for text-to-image generation."

  - name: "FLUX.1 [schnell]"
    path: "black-forest-labs/FLUX.1-schnell"
    description: "FLUX.1 [schnell], optimized for fast inference."

  - name: "Qwen-Image"
    path: "Qwen/Qwen-Image"
    description: "Qwen-Image – realistic, high-quality model."

  - name: "HunyuanImage-3.0"
    path: "tencent/HunyuanImage-3.0"
    description: "Hunyuan Image 3, creative image generation."

  - name: "RunwayML Stable Diffusion v1.5"
    path: "runwayml/stable-diffusion-v1-5"
    description: "Stable Diffusion v1.5 by RunwayML."

  - name: "Juggernaut XL v8"
    path: "trishonc/Juggernaut-XL-v8"
    description: "Juggernaut XL v8, realism engine."

  - name: "Juggernaut XL v9"
    path: "RunDiffusion/Juggernaut-XL-v9"
    description: "Juggernaut XL v9, advanced realism."

  - name: "Juggernaut v10"
    path: "rundiffusion/juggernaut-v10"
    description: "Juggernaut v10 for high performance."

  - name: "Realistic Vision V4"
    path: "SG161222/Realistic_Vision_V4.0"
    description: "Realistic Vision V4, SFW, generalist."

  - name: "Realistic Vision V6"
    path: "rundiffusion/realistic-vision-v6"
    description: "Realistic Vision v6, photorealism focus."

  - name: "RealisticStockPhoto v2.0"
    path: "realisticStockPhoto/realisticStockPhoto_v20"
    description: "Generates realistic stock photos."
